# Generated by Django 5.0.6 on 2024-05-29 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('fec_crea', models.DateTimeField(default=django.utils.timezone.now)),
                ('fec_update', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0.0)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('pass_field', models.CharField(db_column='pass', max_length=40)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
